### ISSUE TITLE
rsCommon not waiting for Service Level Automation to finish

### ISSUE THREAD

**Issue by nick-o** [rsWinAutomationSupport/rsCommon#29]
The Test-rsManaged [Test-rsManaged](https://github.com/rsWinAutomationSupport/rsCommon/blob/master/rsCommon.psm1#L350-L369) Function is not waiting for the Managed Service Level Automation to finish before it carries on. This does cause frequent Servermill failures and affects customer's confidence in the Automation.

The reason this is happening is that after checking for the rax_service_level_automation metadata value once [here](https://github.com/rsWinAutomationSupport/rsCommon/blob/master/rsCommon.psm1#L352) and if this is not defined will never go into the waiting loop [here](https://github.com/rsWinAutomationSupport/rsCommon/blob/master/rsCommon.psm1#L359). The problem with that is that Servermill might take some time to create that metadata and might not have got to it by the time the above function checks and therefore the rsBasePrep.ps1 just carries on.

Part of the solution would probably have to be a way to pass if the account is managed and waiting for the Service Level Automation is necessary. As far as I know we have that information inside rsBasePrep at the time we are calling Test-rsManaged.

**Comment by leshkinski** [comment]
Stealing this issue as it's causing way to many issues for us
